<?php //echo "<pre>";?>
<?php $cart = $this->getCart();?>
<?php $billingAddress = $this->getBillingAddress();?>
<?php //die();?>
<?php $countries = $this->getCountryName();?>
<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
    </div>
    <form id="billingform" method="post" action="<?php echo $this->getUrl('order/adminhtml_order_create/billingaddress',['id'=>$this->getRequest()->getParam('id')])?>">
    <?php echo $this->getBlockHtml('formkey');?>
    <fieldset class="np">

	    <div class="order-address" id="order-billing_address_fields">
	        <div class="content">
	            <div class="hor-scroll">
	                <table cellspacing="0" class="form-list">
	            		<tbody>
							<tr>
	        					<td class="label"><label>First Name <span class="required">*</span></label>
	        					</td>
	    						<td class="value">
	        						<input name="billing[firstname]" <?php if($billingAddress):?> value="<?php echo $billingAddress->firstname ?>" <?php endif;?> class=" required-entry input-text required-entry" type="text" required>           
	    						</td>
							</tr>
									
							<tr>
						        <td class="label"><label>Last Name <span class="required">*</span></label>
						        </td>
								<td class="value">
	    							<input name="billing[lastname]" <?php if($billingAddress):?> value="<?php echo $billingAddress->lastname ?>" <?php endif;?>  class=" required-entry input-text required-entry" type="text" required>            
	    						</td>
	    					</tr>

							<tr>
	        					<td class="label"><label>Street Address <span class="required">*</span></label>
	        					</td>
	    						<td class="value">
									<div class="multi-input">
										<input name="billing[street]" <?php if($billingAddress):?> value="<?php echo $billingAddress->street ?>" <?php endif;?>  class="input-text" type="text" required>
									</div>            
								</td>
	    					</tr>
							<tr>
	        					<td class="label"><label>City <span class="required">*</span></label>
	        					</td>
							    <td class="value">
							        <input  name="billing[city]" <?php if($billingAddress):?> value="<?php echo $billingAddress->city ?>" <?php endif;?>  class=" required-entry input-text required-entry" type="text" required>            
							    </td>
	    					</tr>
	    					<tr>
	        					<td class="label"><label>Country <span class="required">*</span></label>
	        					</td>
							    <td class="value">
							        <select id="shipping_country_id" name="billing[country_id]" class="required-entry required-entry select">
                                    <?php foreach ($countries as $key => $country) : ?>
                                        <option value="<?php echo $country['country_id'];?>" <?php if($billingAddress['country_id'] == $country['country_id']){ echo "selected";} ?> required><?php echo $country['name'];?></option>
                                    <?php endforeach; ?>
                                </select>     
							    </td>
	    					</tr>
						
							<tr>
								<td class="label"><label>State <span class="required" style="display: none;">*</span></label>
								</td>
								<td class="value">
							        <input name="billing[region]" <?php if($billingAddress):?> value="<?php echo $billingAddress->region ?>" <?php endif;?> class=" required-entry input-text required-entry" type="text" required>            
							    </td>
							</tr>
							<tr>
						        <td class="label"><label>ZipCode <span class="required">*</span></label>
						        </td>
							    <td class="value">
							        <input  name="billing[postcode]" <?php if($billingAddress):?> value="<?php echo $billingAddress->postcode ?>" <?php endif;?>  class=" required-entry input-text required-entry" type="number" required>            
							    </td>
						    </tr>
	        			</tbody>
	    			</table>
	        	</div>
	        </div>
	    	<div class="order-save-in-address-book">
	        	<input name="billing[save_in_address_book]" type="checkbox">
	        	<label>Save in address book</label>
	    	</div>
	        	
	    	<div class="form-buttons-left">
	    		<button type="submit" form="billingform"><span>Save Address</span></button>
			</div>
			<div style="display:none;" id="address-billing-overlay" class="overlay"><span>Shipping address selection is not applicable</span>
			</div>
	    </div>
    </fieldset>

	</form>

</div>