<?php $cartData= $this->cartData();?>
<?php //print_r($cartData->getData());?>
<div id="order-items">
	<div class="entry-edit">
		    <div class="grid">
		    	<div class="entry-edit-head">
		   		<h4 class="icon-head head-cart">Cart Data</h4>
		    	<div class="form-buttons"><button type="submit" form="cartform"><span>update Quantity</span></button>
				</div>
			</div>
		        <table cellspacing="0">
		            <thead>
		                <tr class="headings">
		                	<th class="no-link">#</th>
		                    <th class="no-link">Product Name</th>
		                    <th class="no-link">sku</th>
		                    <th class="no-link">Qty</th>
		                    <th class="no-link">Price</th>
		                    <th class="no-link">Discount</th>
		                    <th class="no-link">Base Price</th>

		                    <th class="no-link last">Action</th>
		                </tr>
		            </thead>
		            <form id="cartform" method="get" action="<?php echo $this->getUrl('order/adminhtml_order_create/update',['id'=>$this->getRequest()->getParam('id')])?>">
		            <tbody>
		               		<?php if($cartData):?>
		                	<?php foreach($cartData as $cart):?>
		            		<?php $item_id = $cart->item_id?>
		            		<tr>
							<td><?php echo $cart->item_id;?></td>
							<td><?php echo $cart->name;?></td>
							<td><?php echo $cart->sku;?></td>
							<td><input type="text" name="quantity[<?php echo $cart->item_id ?>]" value="<?php echo $cart->quantity; ?>"></td>
							<td><?php echo $cart->price;?></td>
							<td><?php echo $cart->discount;?></td>
							<td><?php echo $cart->base_price;?></td>
							<td>
								<a href="<?php echo $this->getUrl('order/adminhtml_order_create/deletecart',['id'=>$cart->item_id,'customerId'=>$this->getRequest()->getParam('id')])?>"><button type="button" name="save">delete</button></a>
                     		</td>
							</tr>
							<?php endforeach;?>
						<?php else:;?>
		                    <td class="empty-text a-center" colspan="100">Record not Found</td>
		                <?php endif;?>
		               
		            </tbody>
		        </table>
		    	
		    </div>
	    </form>
    </div>
</div>


