<?php $cart = $this->getCart();?>
<?php //print_r($cart);?>
<?php $items = $cart->getItems();?>
<?php //print_r($items->getData());?>
<?php //die();?>
<div id="order-items">
	<div class="entry-edit">
		    <div class="grid">
		    	<div class="entry-edit-head">
		   		<h4 class="icon-head head-cart">Cart Data</h4>
		    	<div class="form-buttons"><button type="submit" form="cartform"><span>update Quantity</span></button>
				</div>
			</div>
		        <table cellspacing="0">
		            <thead>
		                <tr class="headings">
		                	<th class="no-link">#</th>
		                    <th class="no-link">Product Name</th>
		                    <th class="no-link">sku</th>
		                    <th class="no-link">Qty</th>
		                    <th class="no-link">Price</th>
		                    <th class="no-link">Base Price</th>

		                    <th class="no-link last">Action</th>
		                </tr>
		            </thead>
		            <form id="cartform" method="get" action="<?php echo $this->getUrl('order/adminhtml_order_create/update',['id'=>$this->getRequest()->getParam('id')])?>">
		            <tbody>
		               		<?php if($items):?>
		                	<?php foreach($items as $item):?>
		            		<tr>
							<td><?php echo $item->getId();?></td>
							<td><?php echo $item->getName();?></td>
							<td><?php echo $item->getSku();?></td>
							<td><input type="text" name="quantity[<?php echo $item->item_id ?>]" value="<?php echo $item->getQuantity(); ?>"></td>
							<td><?php echo $item->getPrice();?></td>
							<td><?php echo $item->getBasePrice();?></td>
							<td>
								<a href="<?php echo $this->getUrl('order/adminhtml_order_create/deletecart',['id'=>$item->item_id ,'customer_id' => $this->getRequest()->getParam('id')])?>"><button type="button" name="save">delete</button></a>
                     		</td>
							</tr>
							<?php endforeach;?>
						<?php else:;?>
		                    <td class="empty-text a-center" colspan="100">Record not Found</td>
		                <?php endif;?>
		               
		            </tbody>
		        </table>
		    	
		    </div>
	    </form>
    </div>
</div>


