<div class="entry-edit">
        <div class="entry-edit-head">
            <h4>Add Products</h4>
            <div style="float: right;">
                <button type=button name=button style="float: right;"onclick="productGrid();">Add Product</button>        
            </div>
        </div>
</div>
<div id="product_grid">
	<?php echo $this->getChildHtml('product_grid');?>
</div>

       
    
    

