<?php echo $this->getChildHtml('shippingaddress_form');?>
<?php $cart = $this->getCart();?>
<?php $countries = $this->getCountryName();?>
<?php if($cart):?>
	<?php $cart_id = $cart->getId();?>
<?php endif;?>
<?php $shippingAddress =  $this->getShippingAddress();?>
<?php if($shippingAddress):?>
	<?php $addressId = $shippingAddress->address_id;?>
<?php endif;?>
<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend head-billing-address">Shipping Address</h4>
     </div>
      <form id="shippingform" method="post" action="<?php echo $this->getUrl('order/adminhtml_order_create/shippingaddress',['customer_id'=>$this->getRequest()->getParam('id'),'cart_id'=> $cart_id,'address_id'=>$addressId])?>">
    <?php echo $this->getBlockHtml('formkey');?>
    <fieldset class="np">

    <div class="order-address" id="order-billing_address_fields">
        <div class="content">
                <div class="hor-scroll">
                	<div id="order-shipping_address_choice" class="order-choose-address">
               			<input type="checkbox"  name="shipping[shipping_as_billing]" <?php if($shippingAddress->same_as_billing):?> checked <?php endif;?>>
       					<label for="order-shipping_as_billing" class="no-float">Same As Billing Address</label>
            		</div>
                    <table cellspacing="0" class="form-list">
	            		<tbody>
							<tr>
	        					<td class="label"><label>First Name <span class="required">*</span></label>
	        					</td>
	    						<td class="value">
	        						<input name="shipping[firstname]" <?php if($shippingAddress):?> value="<?php echo $shippingAddress->firstname ?>" <?php endif;?>  class=" required-entry input-text required-entry" type="text">           
	    						</td>
							</tr>
								
							<tr>
							        <td class="label"><label>Last Name <span class="required">*</span></label>
							        </td>
	    							<td class="value">
	        							<input  name="shipping[lastname]" <?php if($shippingAddress):?> value="<?php echo $shippingAddress->lastname ?>" <?php endif;?> class=" required-entry input-text required-entry" type="text">            
	        						</td>
	    					</tr>

							<tr>
	        					<td class="label"><label>Street Address <span class="required">*</span></label>
	        					</td>
	    						<td class="value">
	        						<div class="multi-input"><input name="shipping[street]" <?php if($shippingAddress):?> value="<?php echo $shippingAddress->street ?>" <?php endif;?> class="input-text required-entry" type="text">
									</div>
									           
								</td>
	    					</tr>
							<tr>
	        					<td class="label"><label>City <span class="required">*</span></label>
	        					</td>
							    <td class="value">
							        <input  name="shipping[city]" <?php if($shippingAddress):?> value="<?php echo $shippingAddress->city?>" <?php endif;?> class=" required-entry input-text required-entry" type="text">            
							    </td>
	    					</tr>
	    					<tr>
	        					<td class="label"><label>Country <span class="required">*</span></label>
	        					</td>
							    <td class="value">
							        <select id="shipping_country_id" name="shipping[country_id]" class="required-entry required-entry select">
                                    <?php foreach ($countries as $key => $country) : ?>
                                        <option value="<?php echo $country['country_id'];?>" <?php if($shippingAddress['country_id'] == $country['country_id']){ echo "selected";} ?>><?php echo $country['name'];?></option>
                                    <?php endforeach; ?>
                                </select>                 
							    </td>
	    					</tr>
					
							<tr>
								<td class="label"><label>State <span class="required" style="display: none;">*</span></label>
								</td>
								<td class="value">
							        <input name="shipping[region]" <?php if($shippingAddress):?> value="<?php echo $shippingAddress->region?>" <?php endif;?> class=" required-entry input-text required-entry" type="text">            
							    </td>
							</tr>
							<tr>
						        <td class="label"><label>ZipCode <span class="required">*</span></label>
						        </td>
							    <td class="value">
							        <input name="shipping[postcode]" <?php if($shippingAddress):?> value="<?php echo $shippingAddress->postcode?>" <?php endif;?> class=" required-entry input-text required-entry" type="text">            
							    </td>
						    </tr>

	            		</tbody>
        			</table>
            	</div>
            </div>
        	<div class="order-save-in-address-book">
            	<input name="shipping[save_in_address_book]" type="checkbox" id="order-billing_address_save_in_address_book" value="1">
            	<label for="order-billing_address_save_in_address_book">Save in address book</label>
        	</div>
    	</div>
    	<div class="form-buttons-left">
	    		<button type="submit" form="shippingform"><span>Save Address</span></button>
		</div>
    <div style="display:none;" id="address-billing-overlay" class="overlay"><span>Shipping address selection is not applicable</span></div>
    
    </fieldset>
</form>
</div>

