<?php $cart = $this->getCart();?>
<div style="float: right">  
      <a href="<?php echo $this->getUrl('order/adminhtml_order/index')?>"><button type="button"> Back</button></a>           
      <a href="<?php echo $this->getUrl('order/adminhtml_order/saveorder',['id'=>$this->getRequest()->getParam('id')])?>"><button type="button" name="save"> Submit Order</button></a>
 </div> 
<h3><?php echo $this->getHeaderText(); ?></h3>
             
<hr>

<div>
	<?php echo $this->getChildHtml('product'); ?>
</div>
<hr>
<div>
  <?php echo $this->getChild('cartitem')->setCart($cart)->toHtml(); ?>
</div>
<hr>
<div>
	<?php echo $this->getChild('account')->setCart($cart)->toHtml(); ?>
</div>
<hr>
<div style="display: flex;">
    <div style="width:60%">
      <?php echo $this->getChild('billingaddress')->setCart($cart)->toHtml();?>
    </div>
    <div style="margin-left:20px; width:70%">
       <?php echo $this->getChild('shippingaddress')->setCart($cart)->toHtml(); ?>
    </div>
</div>
<hr>
<div style="display: flex;">
    <div style="width:60%">
      <?php echo $this->getChild('paymentmethod')->setCart($cart)->toHtml(); ?>
    </div>
    <div style="margin-left:20px; width:70%">
       <?php echo $this->getChild('shippingmethod')->setCart($cart)->toHtml(); ?>
    </div>
</div>

<div style="margin-left:470px; width:60%">
  <?php echo $this->getChild('total')->setCart($cart)->toHtml();?>
  
</div>

<!-- <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript">
  var $j = jQuery.noConflict();
  var mage = new Base();
  // alert(1);
</script> -->

<script type="text/javascript">
  document.getElementById('product_grid').style.display = 'none';
  function productGrid(){
    document.getElementById('product_grid').style.display = 'block';
  }
</script>