<?php //echo "<pre>";?>
<?php $order = $this->getOrder();?>
<?php $customer = $order->getCustomer();?>
<?php $billingAddress = $order->getBillingAddress();?>
<?php $countries = $this->getCountryName();?>
<?php $shippingAddress = $order->getShippingAddress();?>
<?php $items = $order->getItems();?>
<?php //print_r($items->getData());?>

<div class="middle" id="anchor-content">
   
    <div class="box-left">
    <!--Order Information-->
		<div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account">Order # <?php echo $order->getId();?> (the order confirmation email was sent)</h4>
            </div>
        	<div class="fieldset">
            	<table cellspacing="0" class="form-list">
	            	<tbody>
	            		<tr>
			                <td class="label"><label>Order Date</label></td>
			                <td class="value"><strong><?php echo $order->created_at?></strong></td>
			            </tr>
	                    <tr>
			                <td class="label"><label>Order Status</label></td>
			                <td class="value"><strong><span id="order_status">Pending</span></strong></td>
			            </tr>
			            
	                </tbody>
            	</table>
        	</div>
   		</div>
	</div>
	<div class="box-right">
    <!--Account Information-->
    	<div class="entry-edit">
       	 	<div class="entry-edit-head">
            	<h4 class="icon-head head-account">Account Information</h4>
            	<!-- <div class="tools"></div> -->
        	</div>
        	<div class="fieldset">
            	<div class="hor-scroll">
                	<table cellspacing="0" class="form-list">
                		<tbody>
                			<tr>
			                    <td class="label"><label>Customer Name</label></td>
			                    <td class="value"><strong><?php echo $customer->firstname.' '.$customer->lastname?></strong></td>
			                </tr>
			                <tr>
			                    <td class="label"><label>Email</label></td>
			                    <td class="value"><a href="<?php echo $customer->getEmail()?>"><strong><?php echo $customer->getEmail()?></strong></a></td>
			                </tr>
                        </tbody>
                    </table>
            	</div>
        	</div>
    	</div>
	</div>
	<div class="clear"></div>

	<div class="box-left">
    <!--Billing Address-->
    	<div class="entry-edit">
        	<div class="entry-edit-head">
            	<h4 class="icon-head head-billing-address">Billing Address</h4>
        	</div>
    		<fieldset>
            	<address><?php echo $billingAddress->getCustomerFirstname().' '.$billingAddress->getCustomerLastname();?><br>
						<?php echo $billingAddress->getAddress();?><br>

						<?php echo $billingAddress->getCity().','.$billingAddress->getRegion().','.$billingAddress->getPostcode();?><br>
						<?php foreach ($countries as $key => $country) : ?>
                            <?php if($billingAddress['country_id'] == $country['country_id']): ?>
                            	<?php echo $country['name'];?>.
                        	<?php endif;?>
                        <?php endforeach; ?>
				</address>
        	</fieldset>
    	</div>
	</div>
	<div class="box-right">
    <!--Shipping Address-->
    	<div class="entry-edit">
        	<div class="entry-edit-head">
            	<h4 class="icon-head head-shipping-address">Shipping Address</h4>
        		<div class="tools"><a href="http://127.0.0.1/magento2/index.php/admin/sales_order/address/address_id/12/key/8e372c03bd6cfb5c74936aec750dd772/">Edit</a>
        		</div>
        	</div>
	        <fieldset>
	            <address><?php echo $shippingAddress->getCustomerFirstname().' '.$shippingAddress->getCustomerLastname();?><br>
						<?php echo $shippingAddress->getAddress();?><br>

						<?php echo $shippingAddress->getCity().','.$shippingAddress->getRegion().','.$shippingAddress->getPostcode();?><br>
						<?php foreach ($countries as $key => $country) : ?>
                            <?php if($shippingAddress['country_id'] == $country['country_id']): ?>
                            	<?php echo $country['name'];?>.
                        	<?php endif;?>
                        <?php endforeach; ?>
				</address>
	        </fieldset>
    	</div>
	</div>
	<div class="clear"></div>
    <input type="hidden" name="order_id" value="6">
        <div class="box-left">
            <!--Payment Method-->
        	<div class="entry-edit">
            	<div class="entry-edit-head">
                	<h4 class="icon-head head-payment-method">Payment Information</h4>
            	</div>
	            <fieldset>
	               <?php echo $order->getPaymentMethodCode();?>
	            </fieldset>
        	</div>
    	</div>
        <div class="box-right">
        <!--Shipping Method-->
        	<div class="entry-edit">
            	<div class="entry-edit-head">
                	<h4 class="icon-head head-shipping-method">Shipping &amp; Handling Information</h4>
           		 </div>
           		<fieldset>
	               
                        <strong><?php echo $order->getShippingMethodCode();?> :</strong>
	                    <span class="price">$ <?php echo $order->getShippingAmount();?></span>                                                
                </fieldset>
        	</div>
   		</div>
        <div class="clear"></div>
        <div class="clear"></div>
    	<div class="entry-edit">
        	<div class="entry-edit-head">
            	<h4 class="icon-head head-products">Items Ordered</h4>
        	</div>
    	</div>
    <div class="grid np">
  	<div class="hor-scroll">
    	<table cellspacing="0" class="data order-tables">
	        <thead>
            	<tr class="headings">
	                <th>Product</th>
	                <th>SKU</th>
	                <th><span class="nobr">Original Price</span></th>
	                <th>Price</th>
	                <th class="a-center">Qty</th>
           		</tr>

        	</thead>
            <tbody class="even">
                
                	<?php foreach($items as $item):?>

                		<tr class="border">
	                		<td><?php echo $item->getName();?></td>
	                		<td><?php echo $item->getSku();?></td>
	                		<td>$<?php echo $item->getBasePrice();?></td>
	                		<td>$<?php echo $item->getPrice();?></td>
	                		<td><?php echo $item->getQuantity();?></td>
                		</tr>
                	<?php endforeach;?>
                		<tr class="border">
                			<!-- <td colspan="2"></td> -->
                			<td colspan="3" class="a-right">Total :- </td>
                			<td>$ <?php echo $order->getTotal();?></td>
                			<td></td>
                		</tr>
            </tbody>
        </table>
  </div>
</div>
<br>
    <div class="clear"></div>

    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4>Comments History</h4>
            </div>
            <fieldset>
            	<div id="order_history_block">
        			<div id="history_form" class="order-history-form">
        				<div>Add Order Comments</div>
        				<span class="field-row">
	           				<label class="normal" for="history_status">Status</label><br>
	            			<select name="history[status]" class="select" id="history_status">
	                            <option value="pending" selected="selected">Pending</option>
	                        </select>
        				</span>
        				<span class="field-row">
	            			<label class="normal" for="history_comment">Comment</label>
	            			<textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment">
	            				
	            			</textarea>
        				</span>
        				
        				<div class="f-right">
            			<button title="Submit Comment" type="button" class="scalable save" ><span><span><span>Submit Comment</span></span></span>
            			</button>        
            		</div>
				</div>
			</fieldset>
        </div>
    </div>
    <div class="box-right entry-edit">
        <div class="entry-edit-head"><h4>Order Totals</h4></div>
        <div class="order-totals">
        	<table cellspacing="0" width="100%">
			    <colgroup>
			    	<col>
			   		<col width="1">
			    </colgroup>
			    <tbody>
				    <tr class="0">
				        <td class="label">Subtotal</td>
				        <td>
				    		<span class="price">$<?php echo $order->getTotal();?></span>                        
				    	</td>
				    </tr>
				    <tr class="1">
				        <td class="label">Shipping &amp; Handling</td>
				        <td>
				            <span class="price">$<?php echo $order->getShippingAmount();?></span>                        
				        </td>
				    </tr>
			    </tbody>

			    <tfoot>

			        <tr class="0">
			            <td class="label">
			                <strong>Grand Total</strong>
			            </td>
			            <td class="emph">
			                <strong><span class="price"><?php echo $order->getTotal() + $order->getShippingAmount();?></span></strong>
			            </td>
			        </tr>
			    </tfoot>
			    
			    
    		</table>
		</div>
	</div>
    <div class="clear"></div>
</div>

